name: TxMongo

on: [push]

jobs:
  basic:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['3.6', '4.2', '4.4']
    steps:
      - uses: actions/checkout@v3
      - name: Start MongoDB on port 27017
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Install tox
        run: pip install tox
      - name: Run basic tests in tox
        run: tox -f basic
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: htmlcov

  advanced:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        mongodb-version: ['3.6', '4.2', '4.4']
    steps:
      - uses: actions/checkout@v3
      - name: Install MongoDB ${{ matrix.mongodb-version }}
        run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-${{ matrix.mongodb-version }}.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/${{ matrix.mongodb-version }} multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-${{ matrix.mongodb-version }}.list
          sudo apt-get update
          sudo apt-get install -y --allow-downgrades mongodb-org-server
      - name: Install Python
        run: |
            sudo apt-get install -y python3 python3-pip
      - name: Install tox and any other packages
        run: pip install tox
      - name: Run advanced tests in tox
        run: tox -f advanced
