name: TxMongo

on: [push]

jobs:
  basic:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['4.2', '4.4']
    steps:
      - uses: actions/checkout@v3
      - name: Start MongoDB (27017)
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Install tox
        run: pip install tox
      - name: Run tests
        run: tox
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: htmlcov
