name: TxMongo With Auth

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10"]
        mongodb-version: ['4.2']

    steps:
      - uses: actions/checkout@v3
      - name: Start MongoDB with Auth (27018)
        uses: supercharge/mongodb-github-action@1.8.0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: pip install tox
      - name: Run tox
        env:
          TXMONGO_TEST_WITH: auth
        run: tox -- tests/test_auth.py